attempted fix which appears to have issues with sharded systems due to inability of mapper to determine which shard to use for delete when multiple entity instances could be on multiple shards. (causes two test cases to fail listed below)
FAILED test/ext/test_horizontal_shard.py::AttachedFileShardTest::test_bulk_delete
FAILED test/ext/test_horizontal_shard.py::DistinctEngineShardTest::test_bulk_delete